version: '2.4'
services:
    # Fizzbuzz API
    fizzbuzz:
        build: .
        image: fizzbuzz
        ports:
            - 8000:8000
        environment:
            APP_PORT: 8000
            DB_HOST: db
            DB_PORT: 5432
            DB_USER: fizzbuzz
            DB_PASSWORD: SecuredPassword
            DB_NAME: fizzbuzz
            JAEGER_SERVICE_NAME: fizzbuzz-api 
            JAEGER_AGENT_HOST: localhost 
            JAEGER_AGENT_PORT: 6831 
            JAEGER_SAMPLER_TYPE: const 
            JAEGER_SAMPLER_PARAM: 1 
        depends_on: 
            db:
               condition: service_healthy
    # Database
    db:
        image: postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: fizzbuzz
            POSTGRES_PASSWORD: SecuredPassword
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U fizzbuzz"]
            interval: 5s
            timeout: 5s
            retries: 5
    # Tracing
    jaeger:
        image: jaegertracing/all-in-one:1.12.0
        ports:
        - 127.0.0.1:5775:5775/udp
        - 127.0.0.1:6831:6831/udp
        - 127.0.0.1:6832:6832/udp
        - 127.0.0.1:5778:5778
        - 127.0.0.1:16686:16686
        - 127.0.0.1:14268:14268
